### ISSUE TITLE
Not Connecting to Thrift Server

### ISSUE THREAD

**Issue by sohimankotia** [wdavidw/node-thrift-hive#3]
Hi I am using following code : 
```

var assert     = require('assert');
var thrift     = require('thrift');
var transport  = require('thrift/lib/nodejs/lib/thrift/transport');
var ThriftHive = require('thrift-hive/lib/0.7.1-cdh3u2/ThriftHive');
// Client connection 
var options = {transport: transport.TBufferedTransport, timeout: 1000 };
var connection = thrift.createConnection('localhost', 10001, options);
var client = thrift.createClient(ThriftHive, connection);
// Execute query 
client.execute('use default', function(err){
    client.execute('show tables', function(err){
        assert.ifError(err);
        client.fetchAll(function(err, databases){
            if(err){
                console.log(err.message);
            }else{
                console.log(databases);
            }
            connection.end();
        });
    });
});
```
Its not working .While debugging also it is showing connect = false .

As I able to connect through beeline :
!connect jdbc:hive2://localhost:10001 hduser hadoop org.apache.hive.jdbc.HiveDriver

Thanks in advance

**Comment by wdavidw** [comment]
This module is connecting to the hive metastore through thrift. The generated thrifs code that we used is old (at least 3 years old) and you'll have to generated the code aligned with your version. See [this directory](https://github.com/wdavidw/node-thrift-hive/tree/master/src). I'havent used this package lately but it shall be working once you get the appropriate generated thrift code.

**Comment by jiacai2050** [comment]
@wdavidw 

How to generate thrift code for a specific hive ?

**Comment by wdavidw** [comment]
good, then i close this issue
